### ISSUE TITLE
On startup it gives this error.

### ISSUE THREAD

**Issue by z1nto** [m3taphor/Bums#11]
BUMS | 2024-11-29 13:13:03 | INFO     | 54 - Searched sessions: 13.
BUMS | 2024-11-29 13:13:03 | SUCCESS  | 64 - Available accounts: 13.
Traceback (most recent call last):
  File "C:\Users\rezya\Desktop\Bums-main\main.py", line 15, in <module>
    asyncio.run(main())
  File "C:\Users\rezya\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\rezya\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rezya\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\rezya\Desktop\Bums-main\main.py", line 10, in main
    await process()
  File "C:\Users\rezya\Desktop\Bums-main\bot\utils\launcher.py", line 58, in process
    await run_tasks(accounts=accounts, used_session_names=used_session_names)
  File "C:\Users\rezya\Desktop\Bums-main\bot\utils\launcher.py", line 65, in run_tasks
    tg_client = await get_tg_client(session_name=session_name, proxy=raw_proxy)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rezya\Desktop\Bums-main\bot\core\registrator.py", line 48, in get_tg_client
    "port": int(proxy.split(":")[4])
                ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Restarting the program in 10 seconds...

**Comment by m3taphor** [comment]
proxy should be in given format
