### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aydinhp1** [m3taphor/Bums#8]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Bums/main.py", line 15, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/home/Bums/main.py", line 10, in main
    await process()
  File "/data/data/com.termux/files/home/Bums/bot/utils/launcher.py", line 58, in process
    await run_tasks(accounts=accounts, used_session_names=used_session_names)
  File "/data/data/com.termux/files/home/Bums/bot/utils/launcher.py", line 70, in run_tasks
    await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/Bums/bot/core/tapper.py", line 888, in run_tapper
    await Tapper(tg_client=tg_client, first_run=first_run).run(user_agent=user_agent, proxy=proxy)
  File "/data/data/com.termux/files/home/Bums/bot/core/tapper.py", line 493, in run
    ref_id, init_data = await self.get_tg_web_data(proxy=proxy)
TypeError: cannot unpack non-iterable NoneType object

**Comment by m3taphor** [comment]
make sure you use **pyrogram** valid session, this error means you have problem in your telegram account and also use python **3.10** with virtual enviroment _as instructed._
